/**
 * Schema Mapper - Intelligent field mapping and validation for data imports
 * Handles schema mismatches, type validation, and automatic field exclusions
 * Enhanced with AI-powered automatic mapping when rule-based matching fails
 */

import { aiColumnMapper, AIColumnMappingResult } from '../services/ai-column-mapper';
import { addressImportService, AddressImportResult } from '../services/address-import-service';
import { secureLogger } from '../utils/secure-logger';

export interface FieldMapping {
  sourceField: string;
  targetField: string;
  dataType: 'string' | 'number' | 'boolean' | 'date' | 'uuid' | 'json';
  required: boolean;
  autoGenerated: boolean;
}

export interface SchemaValidationResult {
  validMappings: FieldMapping[];
  excludedFields: Array<{
    field: string;
    reason: string;
    suggestion?: string;
  }>;
  warnings: string[];
  errors: string[];
  aiMappingUsed?: boolean;
  aiConfidence?: number;
  mappingNotes?: string[];
}

export class SchemaMapper {
  // Address warning aggregation for performance
  private addressWarnings: Map<string, number> = new Map();
  private totalRecordsProcessed: number = 0;
  
  // Define the expected customer schema
  private readonly customerSchema: Record<string, FieldMapping> = {
    id: {
      sourceField: 'id',
      targetField: 'id',
      dataType: 'uuid',
      required: true,
      autoGenerated: true
    },
    firstName: {
      sourceField: 'first_name',
      targetField: 'firstName',
      dataType: 'string',
      required: false,
      autoGenerated: false
    },
    lastName: {
      sourceField: 'last_name',
      targetField: 'lastName',
      dataType: 'string',
      required: false,
      autoGenerated: false
    },
    email: {
      sourceField: 'email',
      targetField: 'email',
      dataType: 'string',
      required: false,
      autoGenerated: false
    },
    phoneNumber: {
      sourceField: 'phone_number',
      targetField: 'phoneNumber',
      dataType: 'string',
      required: false,
      autoGenerated: false
    },
    dateOfBirth: {
      sourceField: 'date_of_birth',
      targetField: 'dateOfBirth',
      dataType: 'date',
      required: false,
      autoGenerated: false
    },
    gender: {
      sourceField: 'gender',
      targetField: 'gender',
      dataType: 'string',
      required: false,
      autoGenerated: false
    },
    currentAddress: {
      sourceField: 'current_address',
      targetField: 'currentAddress',
      dataType: 'json',
      required: false,
      autoGenerated: false
    },
    customerSegment: {
      sourceField: 'customer_segment',
      targetField: 'customerSegment',
      dataType: 'string',
      required: false,
      autoGenerated: false
    },
    lifetimeValue: {
      sourceField: 'lifetime_value',
      targetField: 'lifetimeValue',
      dataType: 'number',
      required: false,
      autoGenerated: false
    },
    dataQualityScore: {
      sourceField: 'data_quality_score',
      targetField: 'dataQualityScore',
      dataType: 'number',
      required: false,
      autoGenerated: false
    }
  };

  // Common field name variations including international formats, cleaned versions, and original camelCase
  private readonly fieldAliases: Record<string, string[]> = {
    'firstName': ['firstName', 'first_name', 'firstname', 'fname', 'given_name', 'nome', 'name', 'nama_depan', 'first'],
    'lastName': ['lastName', 'last_name', 'lastname', 'lname', 'surname', 'family_name', 'sobrenome', 'apellido', 'nama_belakang', 'last'],
    'email': ['email', 'email_address', 'email_addr', 'e_mail', 'mail', 'e-mail', 'correio', 'email_id'],
    'phoneNumber': ['phoneNumber', 'phone', 'phone_number', 'phonenumber', 'telephone', 'mobile', 'cell', 'telefone', 'celular', 'no_telepon', 'contact', 'whatsapp'],
    'dateOfBirth': ['dateOfBirth', 'dob', 'birth_date', 'dateofbirth', 'birthday', 'date_of_birth', 'data_nascimento', 'fecha_nacimiento', 'tanggal_lahir'],
    'gender': ['gender', 'sex', 'sexo', 'genre', 'jenis_kelamin', 'genero'],
    'currentAddress': ['currentAddress', 'address', 'current_address', 'currentaddress', 'location', 'endereco', 'direccion', 'alamat', 'residence'],
    'customerSegment': ['customerSegment', 'segment', 'customer_segment', 'customersegment', 'category', 'type', 'categoria', 'segmento', 'kategori', 'grupo', 'group', 'listener_type', 'audience_type'],
    'lifetimeValue': ['lifetimeValue', 'ltv', 'lifetime_value', 'lifetimevalue', 'customer_value', 'total_value', 'valor_total', 'nilai_pelanggan'],
    'dataQualityScore': ['dataQualityScore', 'quality_score', 'data_quality', 'dataqualityscore', 'quality', 'score', 'pontuacao', 'kualitas']
  };

  /**
   * Enhanced validate and map with AI fallback
   * Automatically uses AI mapping when rule-based mapping fails to map enough fields
   */
  async validateAndMapFieldsWithAI(sourceFields: string[], sampleData: any[] = []): Promise<SchemaValidationResult> {
    // First try rule-based mapping
    const ruleBasedResult = this.validateAndMapFields(sourceFields);

    // Calculate mapping success rate
    const totalFields = sourceFields.length;
    const mappedFields = ruleBasedResult.validMappings.length;
    const mappingRate = totalFields > 0 ? mappedFields / totalFields : 0;

    // If rule-based mapping is successful (>60% mapped), use it
    if (mappingRate >= 0.6) {
      return {
        ...ruleBasedResult,
        aiMappingUsed: false,
        mappingNotes: [`Rule-based mapping: ${mappedFields}/${totalFields} fields mapped`]
      };
    }

    // Rule-based mapping failed, try AI mapping
    secureLogger.info(`🤖 Rule-based mapping insufficient (${mappedFields}/${totalFields}), using AI mapping...`);

    try {
      // Use AI to analyze and map fields
      const aiResult: AIColumnMappingResult = await aiColumnMapper.analyzeFileColumns(
        sourceFields,
        sampleData.slice(0, 50), // Use first 50 rows for analysis
        50
      );

      // Convert AI results to our format
      const aiValidMappings: FieldMapping[] = [];
      const aiExcludedFields: Array<{ field: string; reason: string; suggestion?: string }> = [];
      const warnings: string[] = [];

      for (const aiMapping of aiResult.mappings) {
        if (aiMapping.shouldExclude) {
          aiExcludedFields.push({
            field: aiMapping.originalName,
            reason: aiMapping.exclusionReason || 'AI recommended exclusion',
            suggestion: aiMapping.warnings.join('; ') || undefined
          });
        } else if (aiMapping.suggestedField && aiMapping.confidence > 50) {
          // Map to our schema
          const schemaField = this.findSchemaFieldByTarget(aiMapping.suggestedField);
          if (schemaField) {
            aiValidMappings.push({
              sourceField: aiMapping.originalName,
              targetField: schemaField.targetField,
              dataType: this.mapAIDataTypeToSchema(aiMapping.dataType),
              required: schemaField.required,
              autoGenerated: schemaField.autoGenerated
            });
          }
        }

        // Add warnings for low confidence mappings
        if (aiMapping.confidence < 70 && !aiMapping.shouldExclude) {
          warnings.push(`Low confidence mapping: ${aiMapping.originalName} → ${aiMapping.suggestedField} (${aiMapping.confidence}%)`);
        }
      }

      // Combine rule-based and AI results (AI takes priority for conflicts)
      const combinedMappings = [...aiValidMappings];
      const aiMappedFields = new Set(aiValidMappings.map(m => m.sourceField));

      // Add any rule-based mappings that weren't covered by AI
      for (const ruleMapping of ruleBasedResult.validMappings) {
        if (!aiMappedFields.has(ruleMapping.sourceField)) {
          combinedMappings.push(ruleMapping);
        }
      }

      return {
        validMappings: combinedMappings,
        excludedFields: [...aiExcludedFields, ...ruleBasedResult.excludedFields],
        warnings: [...warnings, ...ruleBasedResult.warnings],
        errors: ruleBasedResult.errors,
        aiMappingUsed: true,
        aiConfidence: aiResult.overallConfidence,
        mappingNotes: [
          `AI mapping used: ${aiValidMappings.length}/${totalFields} fields mapped`,
          `Overall AI confidence: ${aiResult.overallConfidence}%`,
          ...aiResult.processingNotes
        ]
      };

    } catch (error) {
      secureLogger.error('AI mapping failed:', { error: String(error) });
      // Fall back to rule-based result with error
      return {
        ...ruleBasedResult,
        errors: [...ruleBasedResult.errors, `AI mapping failed: ${error instanceof Error ? error.message : 'Unknown error'}`],
        aiMappingUsed: false,
        mappingNotes: [`AI mapping failed, using rule-based mapping: ${mappedFields}/${totalFields} fields`]
      };
    }
  }

  /**
   * Original validate and map method (rule-based only)
   */
  validateAndMapFields(sourceFields: string[]): SchemaValidationResult {
    const result: SchemaValidationResult = {
      validMappings: [],
      excludedFields: [],
      warnings: [],
      errors: []
    };

    // Normalize source field names
    const normalizedFields = sourceFields.map(field => ({
      original: field,
      normalized: this.normalizeFieldName(field)
    }));

    // Check each source field
    for (const { original, normalized } of normalizedFields) {
      const mapping = this.findFieldMapping(normalized);

      if (!mapping) {
        // Check if it's a problematic field that should be excluded
        if (this.shouldExcludeField(original, normalized)) {
          result.excludedFields.push({
            field: original,
            reason: this.getExclusionReason(original, normalized),
            suggestion: this.getFieldSuggestion(normalized)
          });
        } else {
          // Unknown field - include as-is with warning
          result.validMappings.push({
            sourceField: original,
            targetField: normalized,
            dataType: 'string',
            required: false,
            autoGenerated: false
          });
          result.warnings.push(`Unknown field '${original}' will be stored as text`);
        }
      } else if (mapping.autoGenerated) {
        // Auto-generated fields should be excluded
        result.excludedFields.push({
          field: original,
          reason: `Field '${original}' maps to auto-generated database field '${mapping.targetField}'`,
          suggestion: 'This field will be automatically generated by the system'
        });
      } else {
        // Valid mapping
        result.validMappings.push({
          ...mapping,
          sourceField: original
        });
      }
    }

    return result;
  }

  /**
   * Transform a data record based on valid mappings
   *
   * ENHANCEMENT (Aug 13, 2025): Added intelligent address parsing to prevent
   * character-by-character display issue in Customer Profile modals.
   *
   * Two-pass processing:
   * 1. Standard field mapping and conversion
   * 2. Specialized address parsing using AddressImportService
   */
  transformRecord(record: any, validMappings: FieldMapping[]): any {
    const transformed: any = {};

    // First pass: Process all fields
    for (const mapping of validMappings) {
      const sourceValue = record[mapping.sourceField];
      if (sourceValue !== undefined && sourceValue !== null && sourceValue !== '') {
        transformed[mapping.targetField] = this.convertValue(sourceValue, mapping.dataType);
      }
    }

    // Second pass: Enhanced address processing
    this.processAddressFields(record, transformed);

    return transformed;
  }

  /**
   * Process address data with intelligent parsing
   */
  private processAddressFields(record: any, transformed: any): void {
    try {
      // Process address using the address import service
      const addressResult = addressImportService.processAddressFromRow(record);

      if (addressResult.parseSuccess && addressResult.structuredAddress) {
        // Use the properly parsed and structured address
        transformed.currentAddress = addressResult.structuredAddress;
      } else if (addressResult.originalData) {
        // Keep original data if parsing failed but data exists
        transformed.currentAddress = addressResult.originalData;
      }

      // Aggregate address processing warnings for performance
      if (addressResult.warnings.length > 0) {
        addressResult.warnings.forEach(warning => {
          const count = this.addressWarnings.get(warning) || 0;
          this.addressWarnings.set(warning, count + 1);
        });
      }
      this.totalRecordsProcessed++;
    } catch (error) {
      secureLogger.error('Address processing error:', { error: String(error) });
      // Fallback to original logic if address processing fails
    }
  }

  /**
   * Log aggregated address warnings for performance
   */
  logAddressWarningSummary(): void {
    if (this.addressWarnings.size > 0) {
      secureLogger.info(`📍 [Address Parser] Summary for ${this.totalRecordsProcessed} records:`);
      this.addressWarnings.forEach((count, warning) => {
        secureLogger.info(`   • "${warning}": ${count} occurrences`);
      });
    }
    // Reset for next batch
    this.addressWarnings.clear();
    this.totalRecordsProcessed = 0;
  }

  /**
   * Generate user-friendly feedback about schema mapping
   */
  generateMappingFeedback(result: SchemaValidationResult): {
    summary: string;
    details: string[];
    excludedFieldsSummary?: string;
  } {
    const validCount = result.validMappings.length;
    const excludedCount = result.excludedFields.length;
    const warningCount = result.warnings.length;

    const summary = `Mapped ${validCount} fields successfully` +
      (excludedCount > 0 ? `, excluded ${excludedCount} incompatible fields` : '') +
      (warningCount > 0 ? `, ${warningCount} warnings` : '');

    const details: string[] = [];

    // Add valid mappings
    if (validCount > 0) {
      details.push(`✅ Successfully mapped fields: ${result.validMappings.map(m => m.sourceField).join(', ')}`);
    }

    // Add excluded fields with reasons
    if (excludedCount > 0) {
      details.push(`⚠️ Excluded fields:`);
      for (const excluded of result.excludedFields) {
        details.push(`  • ${excluded.field}: ${excluded.reason}`);
        if (excluded.suggestion) {
          details.push(`    💡 ${excluded.suggestion}`);
        }
      }
    }

    // Add warnings
    if (warningCount > 0) {
      details.push(`⚠️ Warnings:`);
      result.warnings.forEach(warning => details.push(`  • ${warning}`));
    }

    const excludedFieldsSummary = excludedCount > 0
      ? `Excluded ${excludedCount} fields: ${result.excludedFields.map(e => e.field).join(', ')}`
      : undefined;

    return {
      summary,
      details,
      excludedFieldsSummary
    };
  }

  private normalizeFieldName(field: string): string {
    return field
      .trim()
      .toLowerCase()
      .replace(/[^\w\s]/g, '')
      .replace(/\s+/g, '_');
  }

  private findFieldMapping(normalizedField: string): FieldMapping | null {
    // Direct match
    for (const [targetField, mapping] of Object.entries(this.customerSchema)) {
      if (mapping.sourceField === normalizedField) {
        return mapping;
      }
    }

    // Alias match
    for (const [targetField, aliases] of Object.entries(this.fieldAliases)) {
      if (aliases.includes(normalizedField)) {
        return this.customerSchema[targetField];
      }
    }

    return null;
  }

  private shouldExcludeField(original: string, normalized: string): boolean {
    // Exclude numeric ID fields that might conflict with UUIDs
    if (normalized === 'id' || normalized === 'customer_id' || normalized === 'record_id') {
      return true;
    }

    // Exclude timestamp fields that are auto-generated
    if (normalized.includes('created_at') || normalized.includes('updated_at')) {
      return true;
    }

    // Exclude system metadata fields
    if (normalized.startsWith('_') || normalized.includes('metadata')) {
      return true;
    }

    return false;
  }

  private getExclusionReason(original: string, normalized: string): string {
    if (normalized === 'id' || normalized === 'customer_id') {
      return 'Numeric ID fields conflict with auto-generated UUID primary keys';
    }
    if (normalized.includes('created_at') || normalized.includes('updated_at')) {
      return 'Timestamp fields are automatically managed by the system';
    }
    if (normalized.startsWith('_')) {
      return 'System metadata fields are reserved';
    }
    return 'Field type incompatible with database schema';
  }

  private getFieldSuggestion(normalized: string): string | undefined {
    if (normalized === 'id') {
      return 'Consider using this as a source reference ID in a separate identifier table';
    }
    if (normalized.includes('date')) {
      return 'Ensure date fields are in YYYY-MM-DD format';
    }
    return undefined;
  }

  private convertValue(value: any, targetType: string): any {
    if (value === null || value === undefined || value === '') {
      return null;
    }

    switch (targetType) {
      case 'number':
        const num = parseFloat(value);
        return isNaN(num) ? null : num;

      case 'boolean':
        if (typeof value === 'boolean') return value;
        const str = String(value).toLowerCase();
        return ['true', 'yes', '1', 'on'].includes(str);

      case 'date':
        try {
          const date = new Date(value);
          return isNaN(date.getTime()) ? null : date;
        } catch {
          return null;
        }

      case 'json':
        try {
          // If it's already an object, return as-is
          if (typeof value === 'object' && value !== null) {
            return value;
          }
          // Try to parse JSON string
          return JSON.parse(String(value));
        } catch {
          // If parsing fails, return as string
          return String(value).trim();
        }

      case 'uuid':
        // Validate UUID format (basic check)
        const uuidStr = String(value).trim();
        const uuidRegex = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
        return uuidRegex.test(uuidStr) ? uuidStr : null;

      case 'string':
      default:
        return String(value).trim();
    }
  }

  /**
   * Find schema field by target field name (for AI mapping integration)
   */
  private findSchemaFieldByTarget(targetField: string): FieldMapping | undefined {
    return Object.values(this.customerSchema).find(field =>
      field.targetField === targetField
    );
  }

  /**
   * Map AI data types to our schema data types
   */
  private mapAIDataTypeToSchema(aiDataType: string): 'string' | 'number' | 'boolean' | 'date' | 'uuid' | 'json' {
    const typeMap: Record<string, 'string' | 'number' | 'boolean' | 'date' | 'uuid' | 'json'> = {
      'text': 'string',
      'email': 'string',
      'phone': 'string',
      'date': 'date',
      'number': 'number',
      'boolean': 'boolean',
      'json': 'json',
      'uuid': 'uuid'
    };

    return typeMap[aiDataType] || 'string';
  }

  /**
   * Map CSV data with cleaned field names to proper database fields
   */
  mapCSVDataToCustomerFields(csvRow: Record<string, any>): {
    mappedFields: Record<string, any>;
    unmappedFields: Record<string, any>;
  } {
    const mappedFields: Record<string, any> = {};
    const unmappedFields: Record<string, any> = {};

    // Create a reverse lookup map from aliases to target fields
    const aliasToTargetField: Record<string, string> = {};
    for (const [targetField, aliases] of Object.entries(this.fieldAliases)) {
      for (const alias of aliases) {
        aliasToTargetField[alias] = targetField;
      }
    }

    for (const [csvField, value] of Object.entries(csvRow)) {
      // Skip internal fields
      if (csvField.startsWith('_')) {
        continue;
      }

      // Try to find target field using aliases
      const targetField = aliasToTargetField[csvField];

      if (targetField && this.customerSchema[targetField]) {
        const schemaField = this.customerSchema[targetField];
        const convertedValue = this.convertValue(value, schemaField.dataType);

        if (convertedValue !== null && convertedValue !== undefined && convertedValue !== '') {
          mappedFields[targetField] = convertedValue;
        }
      } else {
        // Store unmapped fields for custom attributes or JSON storage
        if (value !== null && value !== undefined && value !== '') {
          unmappedFields[csvField] = value;
        }
      }
    }

    return {
      mappedFields,
      unmappedFields
    };
  }

  /**
   * Get all known target field names
   */
  getKnownFieldNames(): string[] {
    return Object.keys(this.customerSchema);
  }
}

export const schemaMapper = new SchemaMapper();
